### ISSUE TITLE
create marker_tag attribute for container_push

### ISSUE THREAD

**Issue by pdeva** [astradot/rules_docker#1]
Modify the `container_push()` rule to add an attribute `marker_tag`. The attribute will be optional.
The `marker_tag` attribute will take the name of a tag. This will be in addition to the tag passed in the `tag` attribute.

When `marker_tag` is specificed, the following needs to happen:

1. When pushing the image, the `marker_tag` is added in addition to the `tag` to the container image.
2. Change behavior of `skip_unchaged_digest`, when it is set to is `true`:

**Current Behavior**

Currently the rule checks the docker repo for a matching image given the sha of the current image. if there is a matching image present, the rule ignores pushing. [Code](https://github.com/bazelbuild/rules_docker/pull/1112/files?diff=split&w=1#diff-e7ac9e82a8d04eaeb4e5aad9adcfd47b1be9ecc3f7ee654e9c1717898842900b)
 

**New Behavior**

If a matching image is found in docker repo, check image tag. If image tag == `marker_tag` then ignore pushing, else push anyway (cause its not the latest image)

### Subtasks:

- [ ] add `marker_tag` optional attribute
- [ ] add `marker_tag` while pushing
- [ ] change behavior of `skip_unchaged_digest`

**Comment by pdeva** [comment]
```
sha= sha256 of image.
markerTag = "latest"

targetTag = "{GIT_COMMIT}-{BUILD_TIMESTAMP}"

//container_push() ensures sha exists in registry

current_tags = getTagSet for sha


// for new push, just done by container_push()
if current_tags.contains(targetTag) && !current_tags.contains(markerTag) {
	current_tags.add(markerTag)
}

// for push that was skipped, that is still actually the latest
// image is already in repo, not push by container_push() cause targetTag is not present.
// its not the head cause it doesnt contain marker tag
if !current_tags.contains(targetTag) && !current_tags.contain(markerTag)   {
	current_tags.add(markerTag)
	current_tags.add(targetTag)	
}

// when change was done in different service, and it should actually be 'skipped',
// state would be: targetTag not present, but contains marker tag
// do nothing, since skip from container_push() was legitimate



change 1  - sha1
service a
{
	var x = 2+2
}

change 2 - sha2
service a
{
	var x = 2+2	
	println("hello")
}

change 3 - sha1
service a
{
	var x = 2+2
}

change 4 - sha6
service x
{
	var x = 3+3
}
```
